language: c

dist: trusty
sudo: false

#sudo: required

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - brew update
    - brew outdated bash || brew upgrade bash

install: autoreconf -i

script:
    - ./configure --prefix=/tmp/jasper && make clean && make && make install
    - make check || (cat test/bin/run_test_*.log; exit 1)

#    - ./configure && make clean && make && make check
