language: c

dist: trusty
sudo: false

#sudo: required

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

install: autoreconf -i

script:
    - ./configure --prefix=/tmp/jasper && make clean && make && make install
    - make check

#    - ./configure && make clean && make && make check
