language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

install: autoreconf -i

script:
    - ./configure --prefix=/tmp/jasper && make clean && make && make install

#    - ./configure && make clean && make && make check
