language: c

dist: trusty
#dist: precise
sudo: false
#group: beta

os:
    - linux
    - osx

#osx_image:
#    - xcode7.3
#    #- xcode8

compiler:
    - clang
    - gcc

before_install:
    - bash --version
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install freeglut; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated bash || brew upgrade bash; fi
#    - bash --version

#install:

script:
    - cmake -DCMAKE_INSTALL_PREFIX=/tmp/jasper . && make clean && make && make install
    - CTEST_OUTPUT_ON_FAILURE=TRUE JAS_ABS_TOP_BUILDDIR="$TRAVIS_BUILD_DIR" JAS_ABS_TOP_SRCDIR="$TRAVIS_BUILD_DIR" JAS_TOP_BUILDDIR="../.." JAS_TOP_SRCDIR="../.." make test || (echo "FAILED"; exit 1)
    - cat Testing/Temporary/LastTest.log

notifications:
    email:
        on_success: change
        on_failure: always

