# version format
version: 1.0.{build}

# build worker image (VM template)
image:
    - Visual Studio 2015
    - Visual Studio 2013

# Scripts that are called at the very beginning, before repository cloning.
init:
    - git config --global core.autocrlf input

configuration:
    - Release
    - Debug

platform:
    - Win64
    #- Win32
    #- x86
    #- x64

#before_build:

#build:
#  verbosity: detailed
#  verbosity: minimal
#  project: INSTALL.vcxproj

build_script:
    - ci\appveyor\build.bat

#build: disabled
